### ISSUE TITLE
Compilation error with Groovy 2.4.6 (Incompatible generic argument types)

### ISSUE THREAD

**Issue by ebourg** [ssadedin/graxxia#2]
Hi,

Matrix.groovy fails to compile with Groovy 2.4.6:

```
/home/ebourg/graxxia/src/main/groovy/graxxia/Matrix.groovy: 438: [Static type checking] - Incompatible generic argument types. Cannot assign java.util.List <Integer> to: java.util.List <Number>
 @ line 438, column 16.
           return keepRows
                  ^

1 error

:compileGroovy FAILED
```

**Comment by ssadedin** [comment]
should compile now - thanks!

**Comment by ebourg** [comment]
Thank you for the quick fix
